-- Demo content for Creative Motion Portfolio (generated by scripts/generate-seed.ts).
-- Run AFTER all files in supabase/migrations (0001, 0002, 0003).
-- Safe to re-run: it clears content tables first. Messages and admins are untouched.
begin;
truncate public.site_settings, public.profile, public.services, public.projects, public.resume_items,
  public.skills, public.testimonials, public.clients, public.pricing_plans, public.blog_posts, public.awards;

insert into public.site_settings (website_name, logo_url, accent_color, default_theme, contact_email, public_phone, seo_title, seo_description, footer_text, hire_label, sections) values
  ('Adrian Vale', null, '#ff014f', 'dark', 'hello@adrianvale.demo', '+44 20 7946 0000', 'Adrian Vale — Creative Designer & Digital Maker', 'Portfolio of Adrian Vale, a creative designer crafting visual identities, interfaces and digital experiences for ambitious brands.', '', 'Hire Me', '[]'::jsonb);

insert into public.profile (full_name, professional_title, typed_roles, short_intro, bio, email, phone, location, profile_image_url, hero_image_url, resume_url, availability_status, social_links, skill_tools) values
  ('Adrian Vale', 'Creative Designer & Digital Maker', array['Designer.', 'Developer.', 'Creative Director.', 'Digital Maker.']::text[], 'I create visual identities, interfaces and digital experiences for ambitious brands and modern products. Motion is my third dimension — I use it to make every interaction feel clear and memorable.', 'I''m a London-based designer with 7+ years of experience helping start-ups and established brands shape how they look, feel and move online. I''m available for freelance work — connect with me via email or phone.', 'hello@adrianvale.demo', '+44 20 7946 0000', 'London / Worldwide', '/demo/portrait.svg', '/demo/portrait.svg', null, 'Available for selected projects', '[{"platform":"facebook","url":"https://facebook.com/"},{"platform":"instagram","url":"https://instagram.com/"},{"platform":"linkedin","url":"https://linkedin.com/"}]'::jsonb, '[{"name":"Figma","icon":"figma"},{"name":"React","icon":"react"},{"name":"Next.js","icon":"nextjs"}]'::jsonb);

insert into public.services (title, short_description, icon_key, active, sort_order) values
  ('Creative Direction', 'I lead the visual story from first idea to launch, keeping every touchpoint consistent and intentional.', 'compass', true, 1),
  ('Web Design', 'Fast, responsive websites with thoughtful layouts, clear hierarchy and motion that guides the eye.', 'monitor', true, 2),
  ('Brand Identity', 'Logos, type systems and colour palettes that give your brand a recognisable, confident voice.', 'pen', true, 3),
  ('Motion Design', 'Micro-interactions and animated storytelling that make products feel alive — never distracting.', 'sparkles', true, 4),
  ('App Development', 'Modern web apps built with React and Next.js, engineered for performance and easy ownership.', 'code', true, 5),
  ('AI Product Visuals', 'Art-directed AI imagery and product visuals, refined by hand to match your brand standards.', 'wand', true, 6);

insert into public.projects (title, slug, category, year, client, role, intro, challenge, solution, result, cover_image_url, gallery, live_url, likes, featured, status, sort_order) values
  ('Nova Labs — Brand Experience', 'nova-labs', 'Brand Experience', 2026, 'Nova Labs', 'Creative Direction, UI Design', 'A complete brand and product experience for a research lab building tools for the next generation of scientists.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-nova-labs.svg', '["/demo/project-nova-labs.svg","/demo/project-morrow-studio.svg"]'::jsonb, 'https://example.com', 600, true, 'published', 1),
  ('Aether Skin — E-commerce Art Direction', 'aether-skin', 'E-commerce', 2025, 'Aether Skin', 'Art Direction, Web Design', 'Art direction and a conversion-focused storefront for a clean-beauty skincare label.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-aether-skin.svg', '["/demo/project-aether-skin.svg","/demo/project-kinetic-house.svg"]'::jsonb, 'https://example.com', 750, true, 'published', 2),
  ('Kinetic House — Digital Product', 'kinetic-house', 'Application', 2025, 'Kinetic House', 'Product Design, Motion', 'A mobile-first booking product for a network of independent design studios.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-kinetic-house.svg', '["/demo/project-kinetic-house.svg","/demo/project-pulse-fitness.svg"]'::jsonb, null, 630, true, 'published', 3),
  ('Nord Form — Identity System', 'nord-form', 'Branding', 2024, 'Nord Form', 'Brand Identity', 'A modular identity system for a Scandinavian furniture studio.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-nord-form.svg', '["/demo/project-nord-form.svg","/demo/project-nova-labs.svg"]'::jsonb, null, 360, false, 'published', 4),
  ('Morrow Studio — Campaign Visuals', 'morrow-studio', 'Campaign', 2024, 'Morrow Studio', 'Creative Direction, AI Visuals', 'A launch campaign mixing art-directed AI imagery with bold editorial typography.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-morrow-studio.svg', '["/demo/project-morrow-studio.svg","/demo/project-aether-skin.svg"]'::jsonb, 'https://example.com', 280, false, 'published', 5),
  ('Pulse Fitness — Mobile App', 'pulse-fitness', 'Application', 2023, 'Pulse', 'UI/UX Design', 'A workout tracking app with playful motion and a focus on daily habits.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-pulse-fitness.svg', '["/demo/project-pulse-fitness.svg","/demo/project-kinetic-house.svg"]'::jsonb, null, 690, false, 'published', 6);

insert into public.resume_items (type, title, subtitle, period, badge, description, active, sort_order) values
  ('education', 'BSc in Graphic Design', 'University of the Arts London', '2014 – 2017', 'First Class', 'Focused on typography, interaction design and visual communication. Graduated with a thesis on motion in interfaces.', true, 1),
  ('education', 'Interaction Design Specialization', 'Online — UC San Diego', '2018', 'Certificate', 'Human-centred design, prototyping and user research methods applied to digital products.', true, 2),
  ('education', 'Advanced Motion Design', 'School of Motion', '2019', 'Certificate', 'Principles of animation, easing and choreography for product and brand work.', true, 3),
  ('experience', 'Senior Product Designer', 'Freelance — Worldwide', '2021 – Present', 'Remote', 'Partnering with start-ups and agencies on brand, product and motion design from concept to launch.', true, 1),
  ('experience', 'Product Designer', 'Kinetic Studio, London', '2018 – 2021', 'Full-time', 'Designed web and mobile products for clients in fintech, retail and culture. Led the internal design system.', true, 2),
  ('experience', 'Junior Designer', 'Nord Agency, London', '2017 – 2018', 'Full-time', 'Brand identity, campaign graphics and website design for local and international brands.', true, 3);

insert into public.skills (name, category, level, active, sort_order) values
  ('UI / UX Design', 'Design Skill', 95, true, 1),
  ('Brand Identity', 'Design Skill', 90, true, 2),
  ('Motion Design', 'Design Skill', 85, true, 3),
  ('Figma', 'Design Skill', 95, true, 4),
  ('React / Next.js', 'Development Skill', 85, true, 5),
  ('TypeScript', 'Development Skill', 80, true, 6),
  ('Tailwind CSS', 'Development Skill', 90, true, 7),
  ('Framer Motion', 'Development Skill', 85, true, 8);

insert into public.testimonials (name, role, company, project_title, quote, avatar_url, rating, active, sort_order) values
  ('Sarah Mitchell', 'Founder', 'Nova Labs', 'Brand Experience', 'Adrian understood our vision faster than any designer we''ve worked with. The new identity gave us the confidence to pitch to much bigger partners — and the motion work is simply beautiful.', '/demo/avatar-1.svg', 5, true, 1),
  ('Daniel Kim', 'Head of Product', 'Kinetic House', 'Digital Product', 'Clear process, great communication and a final product our users love. Bookings grew noticeably within weeks of launch. I''d happily work with Adrian again.', '/demo/avatar-2.svg', 5, true, 2),
  ('Laura Reyes', 'Marketing Director', 'Aether Skin', 'E-commerce Art Direction', 'From the first moodboard to the final storefront, every detail felt considered. Our campaign looked premium across every channel.', '/demo/avatar-3.svg', 5, true, 3);

insert into public.clients (name, category, logo_url, website_url, active, sort_order) values
  ('Nova Labs', 'Brand', '/demo/logo-nova.svg', null, true, 1),
  ('Aether', 'Brand', '/demo/logo-aether.svg', null, true, 2),
  ('Kinetic', 'Product', '/demo/logo-kinetic.svg', null, true, 3),
  ('Nord', 'Brand', '/demo/logo-nord.svg', null, true, 4),
  ('Morrow', 'Campaign', '/demo/logo-morrow.svg', null, true, 5),
  ('Pulse', 'Product', '/demo/logo-pulse.svg', null, true, 6),
  ('Lumen', 'Campaign', '/demo/logo-lumen.svg', null, true, 7),
  ('Orbit', 'Product', '/demo/logo-orbit.svg', null, true, 8);

insert into public.awards (title, organization, year, short_description, image_url, link_url, active, sort_order) values
  ('Design Excellence Award', 'Global Web Awards', '2026', 'Recognised for the Nova Labs brand experience — praised for its bold typography, cinematic motion and seamless responsive layout.', '/demo/award-1.svg', null, true, 1),
  ('Best UI Design', 'CSS Design Honors', '2025', 'Awarded for the Kinetic House booking product, selected by a jury of designers for clarity, usability and visual polish.', '/demo/award-2.svg', null, true, 2),
  ('Motion Design of the Year', 'Digital Craft Awards', '2025', 'Honoured for purposeful micro-interactions that guide users without distraction across web and mobile.', '/demo/award-3.svg', null, true, 3),
  ('Innovation in Branding', 'Brand Impact Forum', '2024', 'Shortlisted and awarded for the Nord Form modular identity system, built to scale from packaging to product.', '/demo/award-4.svg', null, true, 4);

insert into public.pricing_plans (name, tagline, price, period, description, features, cta_label, highlighted, active, sort_order) values
  ('Starter', 'Landing Page', '$990', 'per project', 'A focused one-page website to launch an idea, product or personal brand quickly.', array['1 responsive page', 'Light & dark mode', 'Basic SEO setup', 'Contact form', '7-day delivery']::text[], 'Order Now', false, true, 1),
  ('Standard', 'Brand + Website', '$2,400', 'per project', 'A complete identity and a multi-page website with motion and a simple content dashboard.', array['Logo & brand guide', 'Up to 6 pages', 'Motion & micro-interactions', 'Admin dashboard', 'SEO & analytics', '21-day delivery']::text[], 'Order Now', true, true, 2),
  ('Premium', 'Product Design', '$4,800', 'per project', 'End-to-end product design for web or mobile apps, including prototypes and a design system.', array['Research & strategy', 'UX flows & wireframes', 'High-fidelity UI', 'Interactive prototype', 'Design system', 'Developer handoff']::text[], 'Order Now', false, true, 3);

insert into public.blog_posts (title, slug, excerpt, content, cover_image_url, category, read_time, published_at, status) values
  ('Motion principles that make interfaces feel premium', 'motion-principles-premium-interfaces', 'Animation should explain, not decorate. Here are the five motion rules I use on every product.', 'Good motion is invisible. It answers questions before the user asks them: where did that come from, where did it go, what can I do next?

## 1. Motion supports hierarchy
The most important element should move first. Supporting content follows with a short stagger so the eye has a clear path.

## 2. Prefer transform and opacity
They are cheap for the browser to animate and keep scrolling smooth at 60fps, even on mid-range phones.

## 3. Respect reduced motion
Some people get dizzy from large movements. When the operating system asks for reduced motion, remove non-essential animation entirely.

## 4. Keep durations short
Most UI transitions feel best between 200ms and 500ms. Anything longer should be a deliberate storytelling moment.

## 5. Stop when the job is done
Non-stop animation competes with content. Let things settle so people can read.', '/demo/blog-motion-principles.svg', 'Motion', '4 min read', '2026-05-02', 'published'),
  ('Building a brand system that scales with your product', 'brand-system-that-scales', 'A logo is not a brand. How to design a flexible system that survives real-world use.', 'Most brands break the first time they meet a real product. The logo looks great on a poster, but nobody decided how buttons, charts or empty states should feel.

## Start with principles
Write three words that describe how the brand should feel. Every later decision gets tested against them.

## Design tokens first
Colour, type, spacing and radius should be defined as tokens so design and code share one source of truth.

## Test in context
Put the system into real screens early: a pricing table, an error message, a dark mode dashboard. Those are the moments that reveal gaps.', '/demo/blog-brand-systems.svg', 'Branding', '5 min read', '2026-03-18', 'published'),
  ('Using AI for product visuals without losing your style', 'ai-product-visuals-style', 'AI can speed up art direction — if you treat it like a junior assistant, not the designer.', 'AI image tools are fast, but speed without direction produces generic results. The trick is to keep the creative decisions human.

## Build a visual brief
Collect references, lighting notes and colour palettes before you write a single prompt.

## Iterate in small steps
Change one variable at a time so you learn what actually improves the image.

## Finish by hand
Retouch, colour-grade and composite the final images so they match the rest of the brand perfectly.', '/demo/blog-ai-visuals.svg', 'AI', '3 min read', '2026-01-09', 'published');

commit;

-- ------------------------------------------------------------------
-- Make your dashboard owner (run once, after creating the user in
-- Supabase -> Authentication -> Users). Replace the email below.
-- ------------------------------------------------------------------
-- insert into public.admins (user_id, display_name)
-- select id, 'Adrian Vale' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;
