-- =====================================================================
-- Website installed into schema "site01" (generated by scripts/build-schema-sql.mjs).
-- Storage bucket: "site01-media". Safe to re-run (demo content is reset).
--
-- AFTER running this file:
--   1. Project Settings → Data API → "Exposed schemas": add site01  (then Save)
--   2. Website .env: NEXT_PUBLIC_SUPABASE_SCHEMA=site01
--   3. Make your owner an admin of this website (bottom of this file).
-- =====================================================================

create schema if not exists site01;
grant usage on schema site01 to anon, authenticated, service_role;
alter default privileges in schema site01 grant all on tables to anon, authenticated, service_role;
alter default privileges in schema site01 grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema site01 grant execute on functions to anon, authenticated, service_role;
-- Row Level Security (enabled on every table below) still decides who can read or write.

-- >>> 0001_init.sql
-- =====================================================================
-- Creative Motion Portfolio — initial schema
-- Single-owner portfolio. Public can read published/active content;
-- only users listed in site01.admins (and active) can write.
-- =====================================================================


-- ---------- helpers ----------
create or replace function site01.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------- admins (dashboard users) ----------
create table if not exists site01.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default 'Owner',
  avatar_url text,
  role text not null default 'owner' check (role in ('owner')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function site01.is_admin()
returns boolean
language sql stable security definer set search_path = site01
as $$
  select exists (
    select 1 from site01.admins a where a.user_id = auth.uid() and a.active
  );
$$;
revoke all on function site01.is_admin() from public;
grant execute on function site01.is_admin() to anon, authenticated;

-- ---------- site settings (single row) ----------
create table if not exists site01.site_settings (
  id uuid primary key default gen_random_uuid(),
  website_name text not null,
  logo_url text,
  accent_color text not null default '#ff014f' check (accent_color ~* '^#([0-9a-f]{3}|[0-9a-f]{6})$'),
  default_theme text not null default 'dark' check (default_theme in ('dark', 'light', 'system')),
  contact_email text not null,
  public_phone text,
  seo_title text not null,
  seo_description text not null,
  footer_text text not null default '',
  hire_label text not null default 'Hire Me',
  updated_at timestamptz not null default now()
);

-- ---------- profile (single row) ----------
create table if not exists site01.profile (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  professional_title text not null,
  typed_roles text[] not null default '{}',
  short_intro text not null default '',
  bio text not null default '',
  email text not null,
  phone text,
  location text not null default '',
  profile_image_url text not null,
  hero_image_url text,
  resume_url text,
  availability_status text not null default '',
  social_links jsonb not null default '[]'::jsonb,
  skill_tools jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- content tables ----------
create table if not exists site01.services (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  short_description text not null,
  icon_key text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site01.projects (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  category text not null,
  year int not null,
  client text,
  role text,
  intro text not null,
  challenge text,
  solution text,
  result text,
  cover_image_url text not null,
  gallery jsonb not null default '[]'::jsonb,
  live_url text,
  likes int not null default 0,
  featured boolean not null default false,
  status text not null default 'published' check (status in ('published', 'draft')),
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site01.resume_items (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('education', 'experience')),
  title text not null,
  subtitle text not null,
  period text not null,
  badge text,
  description text not null default '',
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site01.skills (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  level int not null default 80 check (level between 0 and 100),
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site01.testimonials (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  role text,
  company text,
  project_title text,
  quote text not null,
  avatar_url text,
  rating int not null default 5 check (rating between 1 and 5),
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site01.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null default 'Brand',
  logo_url text,
  website_url text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site01.pricing_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  tagline text not null default '',
  price text not null,
  period text not null default '',
  description text not null default '',
  features text[] not null default '{}',
  cta_label text not null default 'Order Now',
  highlighted boolean not null default false,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site01.blog_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  excerpt text not null,
  content text not null,
  cover_image_url text not null,
  category text not null,
  read_time text not null default '3 min read',
  published_at date not null default current_date,
  status text not null default 'published' check (status in ('published', 'draft')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site01.messages (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 80),
  email text not null check (char_length(email) between 5 and 120),
  phone text check (phone is null or char_length(phone) <= 30),
  service text check (service is null or char_length(service) <= 80),
  budget text check (budget is null or char_length(budget) <= 40),
  message text not null check (char_length(message) between 10 and 4000),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------- updated_at triggers ----------
do $$
declare t text;
begin
  foreach t in array array['admins','site_settings','profile','services','projects','resume_items','skills','testimonials','clients','pricing_plans','blog_posts']
  loop
    execute format('drop trigger if exists trg_%1$s_updated on site01.%1$s', t);
    execute format('create trigger trg_%1$s_updated before update on site01.%1$s for each row execute function site01.set_updated_at()', t);
  end loop;
end $$;

-- ---------- Row Level Security ----------
alter table site01.admins enable row level security;
alter table site01.site_settings enable row level security;
alter table site01.profile enable row level security;
alter table site01.services enable row level security;
alter table site01.projects enable row level security;
alter table site01.resume_items enable row level security;
alter table site01.skills enable row level security;
alter table site01.testimonials enable row level security;
alter table site01.clients enable row level security;
alter table site01.pricing_plans enable row level security;
alter table site01.blog_posts enable row level security;
alter table site01.messages enable row level security;

-- admins: a user can read and update only their own row (never role/active via app)
drop policy if exists "admins read self" on site01.admins;
create policy "admins read self" on site01.admins for select to authenticated using (user_id = auth.uid());
drop policy if exists "admins update self" on site01.admins;
create policy "admins update self" on site01.admins for update to authenticated
  using (user_id = auth.uid() and site01.is_admin())
  with check (user_id = auth.uid() and role = 'owner' and active = true);

-- public read policies
drop policy if exists "public read settings" on site01.site_settings;
create policy "public read settings" on site01.site_settings for select using (true);
drop policy if exists "public read profile" on site01.profile;
create policy "public read profile" on site01.profile for select using (true);
drop policy if exists "public read services" on site01.services;
create policy "public read services" on site01.services for select using (active or site01.is_admin());
drop policy if exists "public read projects" on site01.projects;
create policy "public read projects" on site01.projects for select using (status = 'published' or site01.is_admin());
drop policy if exists "public read resume" on site01.resume_items;
create policy "public read resume" on site01.resume_items for select using (active or site01.is_admin());
drop policy if exists "public read skills" on site01.skills;
create policy "public read skills" on site01.skills for select using (active or site01.is_admin());
drop policy if exists "public read testimonials" on site01.testimonials;
create policy "public read testimonials" on site01.testimonials for select using (active or site01.is_admin());
drop policy if exists "public read clients" on site01.clients;
create policy "public read clients" on site01.clients for select using (active or site01.is_admin());
drop policy if exists "public read pricing" on site01.pricing_plans;
create policy "public read pricing" on site01.pricing_plans for select using (active or site01.is_admin());
drop policy if exists "public read posts" on site01.blog_posts;
create policy "public read posts" on site01.blog_posts for select using (status = 'published' or site01.is_admin());

-- admin write policies
do $$
declare t text;
begin
  foreach t in array array['site_settings','profile','services','projects','resume_items','skills','testimonials','clients','pricing_plans','blog_posts']
  loop
    execute format('drop policy if exists "admin insert %1$s" on site01.%1$s', t);
    execute format('create policy "admin insert %1$s" on site01.%1$s for insert to authenticated with check (site01.is_admin())', t);
    execute format('drop policy if exists "admin update %1$s" on site01.%1$s', t);
    execute format('create policy "admin update %1$s" on site01.%1$s for update to authenticated using (site01.is_admin()) with check (site01.is_admin())', t);
    execute format('drop policy if exists "admin delete %1$s" on site01.%1$s', t);
    execute format('create policy "admin delete %1$s" on site01.%1$s for delete to authenticated using (site01.is_admin())', t);
  end loop;
end $$;

-- messages: anyone may submit (validated by CHECK constraints); only admins can read/manage
drop policy if exists "anyone can send message" on site01.messages;
create policy "anyone can send message" on site01.messages for insert to anon, authenticated with check (is_read = false);
drop policy if exists "admin read messages" on site01.messages;
create policy "admin read messages" on site01.messages for select to authenticated using (site01.is_admin());
drop policy if exists "admin update messages" on site01.messages;
create policy "admin update messages" on site01.messages for update to authenticated using (site01.is_admin()) with check (site01.is_admin());
drop policy if exists "admin delete messages" on site01.messages;
create policy "admin delete messages" on site01.messages for delete to authenticated using (site01.is_admin());

-- ---------- Storage ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site01-media',
  'site01-media',
  true,
  5242880, -- 5 MB
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public read media [site01]" on storage.objects;
create policy "public read media [site01]" on storage.objects for select using (bucket_id = 'site01-media');
drop policy if exists "admin upload media [site01]" on storage.objects;
create policy "admin upload media [site01]" on storage.objects for insert to authenticated
  with check (bucket_id = 'site01-media' and site01.is_admin()
    and (storage.foldername(name))[1] in ('profile', 'projects', 'services', 'testimonials', 'clients', 'blog', 'documents', 'settings'));
drop policy if exists "admin update media [site01]" on storage.objects;
create policy "admin update media [site01]" on storage.objects for update to authenticated
  using (bucket_id = 'site01-media' and site01.is_admin());
drop policy if exists "admin delete media [site01]" on storage.objects;
create policy "admin delete media [site01]" on storage.objects for delete to authenticated
  using (bucket_id = 'site01-media' and site01.is_admin());


-- >>> 0002_hardening.sql
-- =====================================================================
-- Security hardening (run after 0001_init.sql). Safe to re-run.
-- =====================================================================

-- ---------- Contact form: database-level anti-spam ----------
-- The anon key is public, so someone could call the REST API directly and
-- skip the website's rate limit. This trigger caps volume in the database.
create or replace function site01.messages_guard()
returns trigger
language plpgsql security definer set search_path = site01
as $$
begin
  -- Clients can never set these themselves.
  new.is_read := false;
  new.created_at := now();

  if (select count(*) from site01.messages where created_at > now() - interval '10 minutes') >= 30 then
    raise exception 'Too many messages right now. Please try again later.' using errcode = 'P0001';
  end if;

  if (select count(*) from site01.messages
      where lower(email) = lower(new.email) and created_at > now() - interval '1 hour') >= 3 then
    raise exception 'Too many messages from this email. Please try again later.' using errcode = 'P0001';
  end if;

  if new.email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Invalid email.' using errcode = 'P0001';
  end if;

  return new;
end $$;

drop trigger if exists trg_messages_guard on site01.messages;
create trigger trg_messages_guard before insert on site01.messages
for each row execute function site01.messages_guard();

create index if not exists messages_created_at_idx on site01.messages (created_at desc);
create index if not exists messages_email_idx on site01.messages (lower(email));

-- ---------- Storage: stop public listing of files ----------
-- Public buckets serve files by URL without any SELECT policy, so only
-- admins need to list objects (the dashboard uses it to delete old files).
drop policy if exists "public read media [site01]" on storage.objects;
drop policy if exists "admin read media [site01]" on storage.objects;
drop policy if exists "admin read media [site01]" on storage.objects;
create policy "admin read media [site01]" on storage.objects for select to authenticated
  using (bucket_id = 'site01-media' and site01.is_admin());

-- ---------- Admins: users may only edit their name / avatar ----------
revoke update on site01.admins from anon, authenticated;
grant update (display_name, avatar_url) on site01.admins to authenticated;


-- >>> 0003_awards_sections.sql
-- =====================================================================
-- Awards + page-section settings (run after 0002_hardening.sql). Safe to re-run.
-- =====================================================================

-- ---------- Awards (optional section) ----------
create table if not exists site01.awards (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  organization text,
  year text,
  short_description text not null,
  image_url text not null,
  link_url text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_awards_updated on site01.awards;
create trigger trg_awards_updated before update on site01.awards
for each row execute function site01.set_updated_at();

alter table site01.awards enable row level security;

drop policy if exists "public read awards" on site01.awards;
drop policy if exists "admin insert awards" on site01.awards;
drop policy if exists "admin update awards" on site01.awards;
drop policy if exists "admin delete awards" on site01.awards;
drop policy if exists "public read awards" on site01.awards;
create policy "public read awards" on site01.awards for select using (active or site01.is_admin());
drop policy if exists "admin insert awards" on site01.awards;
create policy "admin insert awards" on site01.awards for insert to authenticated with check (site01.is_admin());
drop policy if exists "admin update awards" on site01.awards;
create policy "admin update awards" on site01.awards for update to authenticated using (site01.is_admin()) with check (site01.is_admin());
drop policy if exists "admin delete awards" on site01.awards;
create policy "admin delete awards" on site01.awards for delete to authenticated using (site01.is_admin());

-- ---------- Page sections: visibility + order ----------
alter table site01.site_settings
  add column if not exists sections jsonb not null default '[]'::jsonb;

-- ---------- Storage: allow the new "awards" upload folder ----------
drop policy if exists "admin upload media [site01]" on storage.objects;
drop policy if exists "admin upload media [site01]" on storage.objects;
create policy "admin upload media [site01]" on storage.objects for insert to authenticated
  with check (bucket_id = 'site01-media' and site01.is_admin()
    and (storage.foldername(name))[1] in ('profile', 'projects', 'services', 'testimonials', 'clients', 'awards', 'blog', 'documents', 'settings'));


-- >>> seed.sql (demo content)
-- Demo content for Creative Motion Portfolio (generated by scripts/generate-seed.ts).
-- Run AFTER all files in supabase/migrations (0001, 0002, 0003).
-- Safe to re-run: it clears content tables first. Messages and admins are untouched.
begin;
truncate site01.site_settings, site01.profile, site01.services, site01.projects, site01.resume_items,
  site01.skills, site01.testimonials, site01.clients, site01.pricing_plans, site01.blog_posts, site01.awards;

insert into site01.site_settings (website_name, logo_url, accent_color, default_theme, contact_email, public_phone, seo_title, seo_description, footer_text, hire_label, sections) values
  ('Adrian Vale', null, '#ff014f', 'dark', 'hello@adrianvale.demo', '+44 20 7946 0000', 'Adrian Vale — Creative Designer & Digital Maker', 'Portfolio of Adrian Vale, a creative designer crafting visual identities, interfaces and digital experiences for ambitious brands.', '', 'Hire Me', '[]'::jsonb);

insert into site01.profile (full_name, professional_title, typed_roles, short_intro, bio, email, phone, location, profile_image_url, hero_image_url, resume_url, availability_status, social_links, skill_tools) values
  ('Adrian Vale', 'Creative Designer & Digital Maker', array['Designer.', 'Developer.', 'Creative Director.', 'Digital Maker.']::text[], 'I create visual identities, interfaces and digital experiences for ambitious brands and modern products. Motion is my third dimension — I use it to make every interaction feel clear and memorable.', 'I''m a London-based designer with 7+ years of experience helping start-ups and established brands shape how they look, feel and move online. I''m available for freelance work — connect with me via email or phone.', 'hello@adrianvale.demo', '+44 20 7946 0000', 'London / Worldwide', '/demo/portrait.svg', '/demo/portrait.svg', null, 'Available for selected projects', '[{"platform":"facebook","url":"https://facebook.com/"},{"platform":"instagram","url":"https://instagram.com/"},{"platform":"linkedin","url":"https://linkedin.com/"}]'::jsonb, '[{"name":"Figma","icon":"figma"},{"name":"React","icon":"react"},{"name":"Next.js","icon":"nextjs"}]'::jsonb);

insert into site01.services (title, short_description, icon_key, active, sort_order) values
  ('Creative Direction', 'I lead the visual story from first idea to launch, keeping every touchpoint consistent and intentional.', 'compass', true, 1),
  ('Web Design', 'Fast, responsive websites with thoughtful layouts, clear hierarchy and motion that guides the eye.', 'monitor', true, 2),
  ('Brand Identity', 'Logos, type systems and colour palettes that give your brand a recognisable, confident voice.', 'pen', true, 3),
  ('Motion Design', 'Micro-interactions and animated storytelling that make products feel alive — never distracting.', 'sparkles', true, 4),
  ('App Development', 'Modern web apps built with React and Next.js, engineered for performance and easy ownership.', 'code', true, 5),
  ('AI Product Visuals', 'Art-directed AI imagery and product visuals, refined by hand to match your brand standards.', 'wand', true, 6);

insert into site01.projects (title, slug, category, year, client, role, intro, challenge, solution, result, cover_image_url, gallery, live_url, likes, featured, status, sort_order) values
  ('Nova Labs — Brand Experience', 'nova-labs', 'Brand Experience', 2026, 'Nova Labs', 'Creative Direction, UI Design', 'A complete brand and product experience for a research lab building tools for the next generation of scientists.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-nova-labs.svg', '["/demo/project-nova-labs.svg","/demo/project-morrow-studio.svg"]'::jsonb, 'https://example.com', 600, true, 'published', 1),
  ('Aether Skin — E-commerce Art Direction', 'aether-skin', 'E-commerce', 2025, 'Aether Skin', 'Art Direction, Web Design', 'Art direction and a conversion-focused storefront for a clean-beauty skincare label.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-aether-skin.svg', '["/demo/project-aether-skin.svg","/demo/project-kinetic-house.svg"]'::jsonb, 'https://example.com', 750, true, 'published', 2),
  ('Kinetic House — Digital Product', 'kinetic-house', 'Application', 2025, 'Kinetic House', 'Product Design, Motion', 'A mobile-first booking product for a network of independent design studios.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-kinetic-house.svg', '["/demo/project-kinetic-house.svg","/demo/project-pulse-fitness.svg"]'::jsonb, null, 630, true, 'published', 3),
  ('Nord Form — Identity System', 'nord-form', 'Branding', 2024, 'Nord Form', 'Brand Identity', 'A modular identity system for a Scandinavian furniture studio.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-nord-form.svg', '["/demo/project-nord-form.svg","/demo/project-nova-labs.svg"]'::jsonb, null, 360, false, 'published', 4),
  ('Morrow Studio — Campaign Visuals', 'morrow-studio', 'Campaign', 2024, 'Morrow Studio', 'Creative Direction, AI Visuals', 'A launch campaign mixing art-directed AI imagery with bold editorial typography.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-morrow-studio.svg', '["/demo/project-morrow-studio.svg","/demo/project-aether-skin.svg"]'::jsonb, 'https://example.com', 280, false, 'published', 5),
  ('Pulse Fitness — Mobile App', 'pulse-fitness', 'Application', 2023, 'Pulse', 'UI/UX Design', 'A workout tracking app with playful motion and a focus on daily habits.', 'The team needed a fresh visual language that could scale across product, marketing and social — without losing the personality that made early customers fall in love with the brand.', 'We ran a two-week discovery sprint, defined a flexible design system, and prototyped key flows with motion from day one so every stakeholder could feel the experience before a line of production code was written.', 'A cohesive identity and product experience that launched on time. Conversion on the new landing pages rose by 38% and the design system cut new-page production time in half.', '/demo/project-pulse-fitness.svg', '["/demo/project-pulse-fitness.svg","/demo/project-kinetic-house.svg"]'::jsonb, null, 690, false, 'published', 6);

insert into site01.resume_items (type, title, subtitle, period, badge, description, active, sort_order) values
  ('education', 'BSc in Graphic Design', 'University of the Arts London', '2014 – 2017', 'First Class', 'Focused on typography, interaction design and visual communication. Graduated with a thesis on motion in interfaces.', true, 1),
  ('education', 'Interaction Design Specialization', 'Online — UC San Diego', '2018', 'Certificate', 'Human-centred design, prototyping and user research methods applied to digital products.', true, 2),
  ('education', 'Advanced Motion Design', 'School of Motion', '2019', 'Certificate', 'Principles of animation, easing and choreography for product and brand work.', true, 3),
  ('experience', 'Senior Product Designer', 'Freelance — Worldwide', '2021 – Present', 'Remote', 'Partnering with start-ups and agencies on brand, product and motion design from concept to launch.', true, 1),
  ('experience', 'Product Designer', 'Kinetic Studio, London', '2018 – 2021', 'Full-time', 'Designed web and mobile products for clients in fintech, retail and culture. Led the internal design system.', true, 2),
  ('experience', 'Junior Designer', 'Nord Agency, London', '2017 – 2018', 'Full-time', 'Brand identity, campaign graphics and website design for local and international brands.', true, 3);

insert into site01.skills (name, category, level, active, sort_order) values
  ('UI / UX Design', 'Design Skill', 95, true, 1),
  ('Brand Identity', 'Design Skill', 90, true, 2),
  ('Motion Design', 'Design Skill', 85, true, 3),
  ('Figma', 'Design Skill', 95, true, 4),
  ('React / Next.js', 'Development Skill', 85, true, 5),
  ('TypeScript', 'Development Skill', 80, true, 6),
  ('Tailwind CSS', 'Development Skill', 90, true, 7),
  ('Framer Motion', 'Development Skill', 85, true, 8);

insert into site01.testimonials (name, role, company, project_title, quote, avatar_url, rating, active, sort_order) values
  ('Sarah Mitchell', 'Founder', 'Nova Labs', 'Brand Experience', 'Adrian understood our vision faster than any designer we''ve worked with. The new identity gave us the confidence to pitch to much bigger partners — and the motion work is simply beautiful.', '/demo/avatar-1.svg', 5, true, 1),
  ('Daniel Kim', 'Head of Product', 'Kinetic House', 'Digital Product', 'Clear process, great communication and a final product our users love. Bookings grew noticeably within weeks of launch. I''d happily work with Adrian again.', '/demo/avatar-2.svg', 5, true, 2),
  ('Laura Reyes', 'Marketing Director', 'Aether Skin', 'E-commerce Art Direction', 'From the first moodboard to the final storefront, every detail felt considered. Our campaign looked premium across every channel.', '/demo/avatar-3.svg', 5, true, 3);

insert into site01.clients (name, category, logo_url, website_url, active, sort_order) values
  ('Nova Labs', 'Brand', '/demo/logo-nova.svg', null, true, 1),
  ('Aether', 'Brand', '/demo/logo-aether.svg', null, true, 2),
  ('Kinetic', 'Product', '/demo/logo-kinetic.svg', null, true, 3),
  ('Nord', 'Brand', '/demo/logo-nord.svg', null, true, 4),
  ('Morrow', 'Campaign', '/demo/logo-morrow.svg', null, true, 5),
  ('Pulse', 'Product', '/demo/logo-pulse.svg', null, true, 6),
  ('Lumen', 'Campaign', '/demo/logo-lumen.svg', null, true, 7),
  ('Orbit', 'Product', '/demo/logo-orbit.svg', null, true, 8);

insert into site01.awards (title, organization, year, short_description, image_url, link_url, active, sort_order) values
  ('Design Excellence Award', 'Global Web Awards', '2026', 'Recognised for the Nova Labs brand experience — praised for its bold typography, cinematic motion and seamless responsive layout.', '/demo/award-1.svg', null, true, 1),
  ('Best UI Design', 'CSS Design Honors', '2025', 'Awarded for the Kinetic House booking product, selected by a jury of designers for clarity, usability and visual polish.', '/demo/award-2.svg', null, true, 2),
  ('Motion Design of the Year', 'Digital Craft Awards', '2025', 'Honoured for purposeful micro-interactions that guide users without distraction across web and mobile.', '/demo/award-3.svg', null, true, 3),
  ('Innovation in Branding', 'Brand Impact Forum', '2024', 'Shortlisted and awarded for the Nord Form modular identity system, built to scale from packaging to product.', '/demo/award-4.svg', null, true, 4);

insert into site01.pricing_plans (name, tagline, price, period, description, features, cta_label, highlighted, active, sort_order) values
  ('Starter', 'Landing Page', '$990', 'per project', 'A focused one-page website to launch an idea, product or personal brand quickly.', array['1 responsive page', 'Light & dark mode', 'Basic SEO setup', 'Contact form', '7-day delivery']::text[], 'Order Now', false, true, 1),
  ('Standard', 'Brand + Website', '$2,400', 'per project', 'A complete identity and a multi-page website with motion and a simple content dashboard.', array['Logo & brand guide', 'Up to 6 pages', 'Motion & micro-interactions', 'Admin dashboard', 'SEO & analytics', '21-day delivery']::text[], 'Order Now', true, true, 2),
  ('Premium', 'Product Design', '$4,800', 'per project', 'End-to-end product design for web or mobile apps, including prototypes and a design system.', array['Research & strategy', 'UX flows & wireframes', 'High-fidelity UI', 'Interactive prototype', 'Design system', 'Developer handoff']::text[], 'Order Now', false, true, 3);

insert into site01.blog_posts (title, slug, excerpt, content, cover_image_url, category, read_time, published_at, status) values
  ('Motion principles that make interfaces feel premium', 'motion-principles-premium-interfaces', 'Animation should explain, not decorate. Here are the five motion rules I use on every product.', 'Good motion is invisible. It answers questions before the user asks them: where did that come from, where did it go, what can I do next?

## 1. Motion supports hierarchy
The most important element should move first. Supporting content follows with a short stagger so the eye has a clear path.

## 2. Prefer transform and opacity
They are cheap for the browser to animate and keep scrolling smooth at 60fps, even on mid-range phones.

## 3. Respect reduced motion
Some people get dizzy from large movements. When the operating system asks for reduced motion, remove non-essential animation entirely.

## 4. Keep durations short
Most UI transitions feel best between 200ms and 500ms. Anything longer should be a deliberate storytelling moment.

## 5. Stop when the job is done
Non-stop animation competes with content. Let things settle so people can read.', '/demo/blog-motion-principles.svg', 'Motion', '4 min read', '2026-05-02', 'published'),
  ('Building a brand system that scales with your product', 'brand-system-that-scales', 'A logo is not a brand. How to design a flexible system that survives real-world use.', 'Most brands break the first time they meet a real product. The logo looks great on a poster, but nobody decided how buttons, charts or empty states should feel.

## Start with principles
Write three words that describe how the brand should feel. Every later decision gets tested against them.

## Design tokens first
Colour, type, spacing and radius should be defined as tokens so design and code share one source of truth.

## Test in context
Put the system into real screens early: a pricing table, an error message, a dark mode dashboard. Those are the moments that reveal gaps.', '/demo/blog-brand-systems.svg', 'Branding', '5 min read', '2026-03-18', 'published'),
  ('Using AI for product visuals without losing your style', 'ai-product-visuals-style', 'AI can speed up art direction — if you treat it like a junior assistant, not the designer.', 'AI image tools are fast, but speed without direction produces generic results. The trick is to keep the creative decisions human.

## Build a visual brief
Collect references, lighting notes and colour palettes before you write a single prompt.

## Iterate in small steps
Change one variable at a time so you learn what actually improves the image.

## Finish by hand
Retouch, colour-grade and composite the final images so they match the rest of the brand perfectly.', '/demo/blog-ai-visuals.svg', 'AI', '3 min read', '2026-01-09', 'published');

commit;

-- ------------------------------------------------------------------
-- Make your dashboard owner (run once, after creating the user in
-- Supabase -> Authentication -> Users). Replace the email below.
-- ------------------------------------------------------------------
-- insert into site01.admins (user_id, display_name)
-- select id, 'Adrian Vale' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;


-- Tables that already existed before a re-run keep their grants; make sure they are set.
grant select, insert, update, delete on all tables in schema site01 to anon, authenticated, service_role;
revoke update on site01.admins from anon, authenticated;
grant update (display_name, avatar_url) on site01.admins to authenticated;

-- Make the dashboard owner for THIS website (create the user first in Authentication → Users):
-- insert into site01.admins (user_id, display_name)
-- select id, 'Owner Name' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;
