// Generates supabase/seed.sql from src/data/demo.ts so demo content stays in one place.
// Run: npm run seed:generate
import { writeFileSync } from "node:fs";
import * as demo from "../src/data/demo.ts";

type Row = Record<string, unknown>;

function lit(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) {
    return `array[${v.map((x) => lit(x)).join(", ")}]::text[]`;
  }
  if (typeof v === "object") return `${lit(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

const json = (v: unknown) => ({ __raw: `${lit(JSON.stringify(v))}::jsonb` });

function insert(table: string, rows: Row[], omit: string[] = ["id"]) {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]).filter((c) => !omit.includes(c));
  const values = rows
    .map(
      (r) =>
        `  (${cols
          .map((c) => {
            const v = r[c] as any;
            return v && typeof v === "object" && "__raw" in v ? v.__raw : lit(v);
          })
          .join(", ")})`
    )
    .join(",\n");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values};\n\n`;
}

let sql = `-- Demo content for Creative Motion Portfolio (generated by scripts/generate-seed.ts).
-- Run AFTER all files in supabase/migrations (0001, 0002, 0003).
-- Safe to re-run: it clears content tables first. Messages and admins are untouched.
begin;
truncate public.site_settings, public.profile, public.services, public.projects, public.resume_items,
  public.skills, public.testimonials, public.clients, public.pricing_plans, public.blog_posts, public.awards;

`;
sql += insert("site_settings", [{ ...demo.demoSettings, sections: json(demo.demoSettings.sections) }]);
sql += insert("profile", [
  { ...demo.demoProfile, social_links: json(demo.demoProfile.social_links), skill_tools: json(demo.demoProfile.skill_tools) },
]);
sql += insert("services", demo.demoServices as Row[]);
sql += insert("projects", demo.demoProjects.map((p) => ({ ...p, gallery: json(p.gallery) })));
sql += insert("resume_items", demo.demoResume as Row[]);
sql += insert("skills", demo.demoSkills as Row[]);
sql += insert("testimonials", demo.demoTestimonials as Row[]);
sql += insert("clients", demo.demoClients as Row[]);
sql += insert("awards", demo.demoAwards as Row[]);
sql += insert("pricing_plans", demo.demoPricing as Row[]);
sql += insert("blog_posts", demo.demoPosts as Row[]);
sql += `commit;

-- ------------------------------------------------------------------
-- Make your dashboard owner (run once, after creating the user in
-- Supabase -> Authentication -> Users). Replace the email below.
-- ------------------------------------------------------------------
-- insert into public.admins (user_id, display_name)
-- select id, 'Adrian Vale' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log("supabase/seed.sql written");
